### PR TITLE
Upgrade to .Net Standard 2.0

### PR DESCRIPTION
**Pull request by sujitn**
- target all projects to .net standard 2.0
- move tests proj to .net 472

### CODE REVIEW

**Comment by ahmedatia** [comment]
Hello Kent @kentcb ... are you considering this pull request?

**Comment by kentcb** [comment]
@sujitn Sorry, I completely missed this. Thanks for the prompt @ahmedatia.

Just so I'm clear, what's the actual advantage of upgrading from NS1 to NS2? Are there any use cases that are unlocked by that?

**Comment by sujitn** [comment]
Cannot use data extension in .net core projects till we upgrade to ns2

**Comment by ahmedatia** [comment]
Thanks @kentcb ... Yep! NS2 introduced more API surface comparing to NS1 and this makes it much easier to port projects to / target .NET Core.

**Comment by kentcb** [comment]
Thanks @sujitn !

**Pull request merged**
